export const  Packages_Action={
    NEW:"NEW",
    SHOW:"SHOW_PACKAGES",
    LOADNEW:"LOAD_NEW",
    LOADSHOW:"LOAD_SHOW",
    UPDATED:"UPDATED",
    SUCCESS:"SUCCESS",
    FAILED:"FAILED",
    UNDERUPDATE:"UNDERUPDATE"
}
export const  Packages_Status={
    NEW:"NEW",
    SUCCESS:"SUCCESS",
    LOADSHOW:"LOAD_SHOW",
    UPDATED:"UPDATED",
    SHOW:"SHOW_PACKAGES",
    FAILED:"FAILED",
    UNDERUPDATE:"UNDERUPDATE"
}