export const  Products_Action={
    NEW:"NEW_PRODUCTS",
    SHOW:"SHOW_Products",
    LOADNEW:"LOAD_NEW",
    DELETE:'DELETE',
    LOADSHOW:"LOAD_SHOW",
    UPDATED:"UPDATED",
    SUCCESS:"SUCCESS",
    FAILED:"FAILED",
    UNDERUPDATE:"UNDERUPDATE"
}
export const  Products_Status={
    NEW:"NEW_PRODUCTS",
    SHOW:"SHOW_Products",
    SUCCESS:"SUCCESS",
    DELETE:'DELETE',
    LOADSHOW:"LOAD_SHOW",
    UPDATED:"UPDATED",    
    FAILED:"FAILED",
    UNDERUPDATE:"UNDERUPDATE"
}