export const Order_Action = {
    SHOW:'SHOW ORDERS',
    SHOW_PENDING:'SHOW_PENDING',
    SHOW_VISITED:'SHOW_VISITED',
    SHOW_PRODUCTIVE:'SHOW_PRODUCTIVE',
    FAILED:"FAILED",
}

export const Order_Status = {
    SHOW:'SHOW ORDERS',
    SHOW_PENDING:'SHOW_PENDING',
    SHOW_VISITED:'SHOW_VISITED',
    SHOW_PRODUCTIVE:'SHOW_PRODUCTIVE',
    FAILED:"FAILED",
}